### ISSUE TITLE
Doesnt seem to work on Ubuntu 13.10

### ISSUE THREAD

**Issue by mayuroks** [chrisfsampaio/imsg#26]
On Ubuntu 13.10 I tried ruby v1.8, v1.9, v2.1 for installing imsg using gem install imsg and it failed on all giving a common error msg.

``` bash
Building native extensions.  This could take a while...
ERROR:  Error installing imsg:
    ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.8 extconf.rb
create /var/lib/gems/1.8/gems/rb-appscript-0.6.1/src/osx_ruby.h ...
create /var/lib/gems/1.8/gems/rb-appscript-0.6.1/src/osx_intern.h ...
creating Makefile

make
Makefile:184: warning: overriding commands for target `/var/lib/gems/1.8/gems/rb-appscript-0.6.1/lib'
Makefile:182: warning: ignoring old commands for target `/var/lib/gems/1.8/gems/rb-appscript-0.6.1/lib'
gcc  -I. -I/usr/lib/ruby/1.8/x86_64-linux -I/usr/lib/ruby/1.8/x86_64-linux -Isrc -D_FORTIFY_SOURCE=2   -fPIC -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -fno-optimize-sibling-calls -fno-tree-dce -fno-strict-aliasing -g -g -O2  -fPIC  -Wall  -c src/SendThreadSafe.c
In file included from src/SendThreadSafe.c:75:0:
src/SendThreadSafe.h:73:53: fatal error: ApplicationServices/ApplicationServices.h: No such file or directory
 #include <ApplicationServices/ApplicationServices.h>
                                                     ^
compilation terminated.
make: *** [SendThreadSafe.o] Error 1
```

I am very new to Ruby. But I did some googling and found that rb-appscript is a gem that is supposed to be compatible only with MAC OSX. I might be wrong but still please can you look at the error and tell me if there's anything to be fixed ?
